version: '3'
services:
  influxdb:
    image: influxdb:2.6-alpine
    env_file:
      - ./influx/influxv2.env
    container_name: influxdb
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influx/data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  mosquitto:
    image: my-mosquitto-image:latest
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT port
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data  # Persist Mosquitto data
      - ./mosquitto/log:/mosquitto/log    # Persist Mosquitto logs
    restart: always  # Restart policy

  telegraf:
    image: telegraf:1.25-alpine
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Mount Telegraf config file
    depends_on:
      - influxdb
      - mosquitto
    restart: always  # Restart policy

volumes:
  influxdb_data:
  mosquitto_data:
  mosquitto_logs:
