# Use the official Mosquitto image from Docker Hub
FROM eclipse-mosquitto

# Expose MQTT port
EXPOSE 1883

# Copy your custom configuration file if needed
COPY config/mosquitto.conf /mosquitto/config/mosquitto.conf
